env:
  browser: true
  es6: true
extends:
  - plugin:react/recommended
  - plugin:jest/recommended
  - airbnb-base
  - prettier
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - react-hooks
  - prettier
rules:
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn
  prettier/prettier: error
